version: '2.4'
services:

  server:
    image: ghcr.io/arnaudparant/sel_server:v7.17.1
    environment:
      - "ES_HOSTS=http://elasticsearch"
      - "ES_AUTH=sel:onlyfortests"
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "9000:9000"

  elasticsearch:
    image: elasticsearch:7.17.18
    command: elasticsearch
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
      - $PWD/tests/config:/config:rw
    environment:
      - ES_PATH_CONF=/config
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
