version: '2.4'
services:

  server:
    image: ghcr.io/arnaudparant/sel_server:v5.5.1
    environment:
      - "ES_HOST=http://elasticsearch"
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "9000:9000"

  elasticsearch:
    image: elasticsearch:5.5
    command: elasticsearch
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

